### ISSUE TITLE
IlmImf won't compile on Mac OS X 10.5

### ISSUE THREAD

**Issue by barretpj** [openexr/openexr#59]
Mac OS X 10.5 lacks posix_memalign(), so compilation fails:

g++ -dynamic -no-cpp-precomp -falign-loops=16 -pipe -Wall -g -O0 -DFLDEBUG -DBUGHUNT -D_REENTRANT -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I. -I../config -I/Users/philb/4.4/build/baselight/Darwin-gcc-4.0.1-64/debug/include/OpenEXR -D_THREAD_SAFE -I.. -I../config -I/Users/philb/4.4/build/baselight/Darwin-gcc-4.0.1-64/debug/include -arch x86_64 -m64 -DCONFIG_64_BIT -DFL_LITTLE_ENDIAN -fPIC -pipe -g -O2 -c ImfScanLineInputFile.cpp -o ImfScanLineInputFile.o
ImfSystemSpecific.h: In function 'void\* Imf_2_0::EXRAllocAligned(size_t, size_t)':
ImfSystemSpecific.h:64: error: 'posix_memalign' was not declared in this scope
make[2]: **\* [ImfScanLineInputFile.lo] Error 1
