### ISSUE TITLE
Build error with g++ 4

### ISSUE THREAD

**Issue by fabiencastan** [openexr/openexr#291]
When trying to build the develop branch with g++ 4.9, I get troubles on `atomic_*`.

```
/tmp/AliceVision/build/openexr/IlmBase/IlmThread/IlmThreadPool.cpp: In member function ‘IlmThread_2_2::ThreadPool::Data::SafeProvider IlmThread_2_2::ThreadPool::Data::getProvider()’:
/tmp/AliceVision/build/openexr/IlmBase/IlmThread/IlmThreadPool.cpp:564:96: error: no matching function for call to ‘atomic_load_explicit(IlmThread_2_2::ThreadPool::Data::TPPointer*, std::memory_order)’
     return SafeProvider( this, std::atomic_load_explicit( &provider, std::memory_order_relaxed ) );
```

https://stackoverflow.com/questions/34205880/why-does-atomic-load-with-a-shared-ptr-not-compile-with-gcc-4-9

The problem has been introduced with the ThreadPool improvements:
https://github.com/openexr/openexr/commit/3019fea12dabd63233c4667c9ebe1564d7f6a15c

I don't know if there is a simple way to keep compatibility with g++ 4.

**Comment by kdt3rd** [comment]
I was expecting those changes to work with gcc 4.8 and newer, but I think I remember there being an issue with gcc 4 and missing atomic functions. Will investigate...

**Comment by kdt3rd** [comment]
believe this to be remedied, no comms indicating otherwise

**Comment by fabiencastan** [comment]
Hi @kdt3rd,
Sorry, I missed your message saying that you made a fix.
Which branch should I test? Is it already in the "develop" branch?
Thanks!
