### ISSUE TITLE
IexMath won't compile on Mac OS X 10.5

### ISSUE THREAD

**Issue by barretpj** [openexr/openexr#58]
It's fine on later OS X versions, but on 10.5 (where I have to compile for historical reasons) it fails. Luckily I don't actually need it :-)

g++ -dynamic -no-cpp-precomp -falign-loops=16 -pipe -Wall -g -O0 -DFLDEBUG -DBUGHUNT -D_REENTRANT -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I. -I../config -I.. -I../Iex -I../config -I/Users/philb/4.4/build/baselight/Darwin-gcc-4.0.1-64/debug/include -arch x86_64 -m64 -DCONFIG_64_BIT -DFL_LITTLE_ENDIAN -fPIC -pipe -g -O2 -D_THREAD_SAFE -c IexMathFpu.cpp -o IexMathFpu.o
IexMathFpu.cpp:278:28: error: asm/sigcontext.h: No such file or directory
IexMathFpu.cpp: In function 'void Iex_2_0::FpuControl::restoreControlRegs(const ucontext_t&, bool)':
IexMathFpu.cpp:283: error: request for member 'fpregs' in 'ucon->__darwin_ucontext::uc_mcontext', which is of non-class type '__darwin_mcontext64\* const'
IexMathFpu.cpp:285: error: '_fpstate' was not declared in this scope
IexMathFpu.cpp:285: error: 'kfp' was not declared in this scope
IexMathFpu.cpp:285: error: expected type-specifier before '_fpstate'
IexMathFpu.cpp:285: error: expected `>' before '_fpstate'
IexMathFpu.cpp:285: error: expected`(' before '_fpstate'
IexMathFpu.cpp:285: error: expected primary-expression before '>' token
IexMathFpu.cpp:285: error: request for member 'fpregs' in 'ucon->__darwin_ucontext::uc_mcontext', which is of non-class type '__darwin_mcontext64\* const'
IexMathFpu.cpp:285: error: expected `)' before ';' token
IexMathFpu.cpp: In function 'void Iex_2_0::setFpExceptionHandler(void (_)(int, const char_))':
IexMathFpu.cpp:466: error: 'SA_NOMASK' was not declared in this scope
IexMathFpu.cpp:468: error: 'struct sigaction' has no member named 'sa_restorer'
make[3]: **\* [IexMathFpu.lo] Error 1
